const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage();const requests=[];const pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('file:'))requests.push(r.url())});await page.goto('file://'+path.resolve('index.html'));await page.waitForFunction(()=>document.querySelectorAll('#nav button').length===10);
for(const width of [320,375,768,1024,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+width)}
const nav=page.locator('#nav button');assert.equal(await nav.count(),10);for(let i=0;i<10;i++){await nav.nth(i).click();assert.equal(await nav.nth(i).getAttribute('aria-pressed'),'true');const txt=(await page.locator('#panel').innerText()).trim();assert.ok(txt.length>10,'module '+(i+1)+' panel too short: '+JSON.stringify(txt)+' pageErrors='+JSON.stringify(pageErrors))}
await nav.nth(1).click();await page.getByLabel('ค้นหางาน').fill('บทความ');assert.equal(await page.locator('#panel .item').count(),1);await page.getByLabel('ค้นหางาน').fill('');await page.getByLabel('กรองสถานะ').selectOption('รอตรวจสอบ');assert.equal(await page.locator('#panel .item').count(),1);
await page.getByLabel('กรองสถานะ').selectOption('ทั้งหมด');await page.locator('#draft').fill('Synthetic browser smoke');await page.locator('#capture button').click();assert.match(await page.locator('#status').innerText(),/สร้างข้อเสนอแล้ว/);assert.match(await page.locator('#smart-preview').innerText(),/Synthetic browser smoke/);await page.getByRole('button',{name:'ยืนยันและบันทึก'}).click();assert.match(await page.locator('#panel').innerText(),/Synthetic browser smoke/);
await page.locator('#draft').fill('วันศุกร์นี้มีสอน HERE 1101');await page.locator('#capture button').click();const preview=await page.locator('#smart-preview').innerText();assert.match(preview,/HERE 1101/);assert.match(preview,/ต้องยืนยันรหัสวิชา/);assert.match(preview,/Teaching Session/);await page.getByRole('button',{name:'ยืนยันและบันทึก'}).click();assert.match(await page.locator('#status').innerText(),/Task \+ Calendar \+ Workflow/);await nav.nth(3).click();assert.match(await page.locator('#panel').innerText(),/HERE 1101/);
await nav.nth(4).click();assert.match(await page.locator('#panel').innerText(),/Document Lifecycle/);assert.match(await page.locator('#panel').innerText(),/Document Intake/);assert.ok(await page.getByLabel('เลือกเอกสารจำลอง').count());
await nav.nth(7).click();await page.getByRole('button',{name:'อนุมัติจำลอง'}).click();assert.match(await page.locator('#panel').innerText(),/อนุมัติจำลอง/);
await nav.nth(0).click();await page.keyboard.press('Tab');const focused=await page.evaluate(()=>document.activeElement?.tagName);assert.ok(['BUTTON','INPUT','SELECT'].includes(focused),'keyboard focus must reach a control');await page.evaluate(()=>{const n=document.querySelector('#nav');if(!n?.getAttribute('aria-label'))throw Error('navigation landmark unlabeled');if(!document.querySelector('[role=status]'))throw Error('missing status region');if(!document.querySelector('main'))throw Error('missing main landmark')});
await page.reload();assert.doesNotMatch(await page.locator('#panel').innerText(),/Synthetic browser smoke/);assert.doesNotMatch(await page.locator('body').innerText(),/HERE 1101/);await nav.nth(7).click();assert.match(await page.locator('#panel').innerText(),/รอพิจารณา/);const authBase='https://ep-blue-leaf-b34hv87k.neonauth.c-4.ap-southeast-1.aws.neon.tech/neondb/auth/';assert.ok(requests.every(u=>u.startsWith(authBase)),'browser emitted an unapproved external request');assert.ok(requests.every(u=>u===authBase+'get-session'),'smoke test may only perform passive session checks');console.log('PASS: ten modules, responsive widths, workflow interactions, reload reset, and only approved passive Neon Auth session checks');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
