-- NEXA FP-16 Notification & Daily Brief Persistence Foundation
CREATE TABLE public.notification_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,created_by uuid NOT NULL,rule_class text NOT NULL CHECK(rule_class IN ('daily_brief','deadline','event','exception')),source_type text,source_id uuid,channel text NOT NULL DEFAULT 'in_app' CHECK(channel='in_app'),timezone text NOT NULL DEFAULT 'Asia/Bangkok',quiet_start time,quiet_end time,snoozed_until timestamptz,threshold_days integer[] NOT NULL DEFAULT ARRAY[7,3,1],enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),CHECK ((quiet_start IS NULL)=(quiet_end IS NULL)));
CREATE TABLE public.notification_intents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,rule_id uuid REFERENCES public.notification_rules(id) ON DELETE SET NULL,created_by uuid NOT NULL,source_type text,source_id uuid,brief_date date,dedupe_key text NOT NULL CHECK(length(btrim(dedupe_key))>0),severity text NOT NULL DEFAULT 'normal' CHECK(severity IN ('low','normal','high')),status text NOT NULL DEFAULT 'generated' CHECK(status IN ('generated','suppressed','read','dismissed')),summary text NOT NULL,detail_ref text,generated_at timestamptz NOT NULL DEFAULT now(),suppression_reason text,UNIQUE(workspace_id,dedupe_key));
ALTER TABLE public.notification_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_intents ENABLE ROW LEVEL SECURITY;
CREATE POLICY notification_rules_member_select ON public.notification_rules FOR SELECT TO authenticated USING(is_workspace_member(workspace_id));
CREATE POLICY notification_rules_creator_insert ON public.notification_rules FOR INSERT TO authenticated WITH CHECK(created_by=current_user_id() AND is_workspace_member(workspace_id));
CREATE POLICY notification_rules_creator_update ON public.notification_rules FOR UPDATE TO authenticated USING(created_by=current_user_id() AND is_workspace_member(workspace_id)) WITH CHECK(created_by=current_user_id() AND is_workspace_member(workspace_id));
CREATE POLICY notification_intents_member_select ON public.notification_intents FOR SELECT TO authenticated USING(is_workspace_member(workspace_id));
CREATE POLICY notification_intents_creator_insert ON public.notification_intents FOR INSERT TO authenticated WITH CHECK(created_by=current_user_id() AND is_workspace_member(workspace_id));
CREATE POLICY notification_intents_creator_update ON public.notification_intents FOR UPDATE TO authenticated USING(created_by=current_user_id() AND is_workspace_member(workspace_id)) WITH CHECK(created_by=current_user_id() AND is_workspace_member(workspace_id));
CREATE OR REPLACE FUNCTION public.nexa_compose_task_notification(p_task_id uuid,p_rule_id uuid,p_due_date date,p_as_of date DEFAULT CURRENT_DATE) RETURNS uuid LANGUAGE plpgsql SECURITY INVOKER AS $$ DECLARE t public.tasks%ROWTYPE; r public.notification_rules%ROWTYPE; v_days integer; v_status text; v_reason text; v_key text; v_id uuid; BEGIN SELECT * INTO t FROM public.tasks WHERE id=p_task_id; IF NOT FOUND THEN RAISE EXCEPTION 'task not found'; END IF; SELECT * INTO r FROM public.notification_rules WHERE id=p_rule_id; IF NOT FOUND THEN RAISE EXCEPTION 'rule not found'; END IF; IF t.workspace_id<>r.workspace_id THEN RAISE EXCEPTION 'workspace mismatch'; END IF; v_days:=p_due_date-p_as_of; v_status:='generated'; v_reason:=NULL; IF t.status IN ('completed','cancelled','done') THEN v_status:='suppressed'; v_reason:='source_not_actionable'; ELSIF NOT r.enabled THEN v_status:='suppressed'; v_reason:='rule_disabled'; ELSIF r.snoozed_until IS NOT NULL AND r.snoozed_until>now() THEN v_status:='suppressed'; v_reason:='snoozed'; ELSIF r.rule_class='deadline' AND NOT (v_days=ANY(r.threshold_days)) THEN v_status:='suppressed'; v_reason:='outside_threshold'; END IF; v_key:='task:'||t.id::text||':due:'||p_due_date::text||':asof:'||p_as_of::text; INSERT INTO public.notification_intents(workspace_id,rule_id,created_by,source_type,source_id,brief_date,dedupe_key,severity,status,summary,detail_ref,suppression_reason) VALUES(t.workspace_id,r.id,r.created_by,'task',t.id,p_as_of,v_key,CASE WHEN v_days<=1 THEN 'high' ELSE 'normal' END,v_status,t.title,'nexa://task/'||t.id::text,v_reason) ON CONFLICT(workspace_id,dedupe_key) DO UPDATE SET generated_at=public.notification_intents.generated_at RETURNING id INTO v_id; RETURN v_id; END $$;